import React from 'react'

const Header = () => {
    return (
        <svg
            className="header"
            width="360px"
            height="101px"
            viewBox="0 0 396 101"
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <title>Custom Preset 3</title>
            <defs>
                <text
                    id="text-1"
                    font-family="Skia-Regular_Bold, Skia"
                    font-size="58"
                    font-weight="bold"
                    fill="#F06C00"
                >
                    <tspan x="129" y="69">
                        N
                    </tspan>
                </text>
                <filter
                    x="-13.4%"
                    y="-7.2%"
                    width="126.8%"
                    height="119.7%"
                    filterUnits="objectBoundingBox"
                    id="filter-2"
                >
                    <feOffset
                        dx="0"
                        dy="2"
                        in="SourceAlpha"
                        result="shadowOffsetOuter1"
                    ></feOffset>
                    <feGaussianBlur
                        stdDeviation="2"
                        in="shadowOffsetOuter1"
                        result="shadowBlurOuter1"
                    ></feGaussianBlur>
                    <feColorMatrix
                        values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.5 0"
                        type="matrix"
                        in="shadowBlurOuter1"
                    ></feColorMatrix>
                </filter>
                <text
                    id="text-3"
                    font-family="Skia-Regular_Bold, Skia"
                    font-size="58"
                    font-weight="bold"
                    fill="#F06C00"
                >
                    <tspan x="5" y="69">
                        A
                    </tspan>
                </text>
                <filter
                    x="-18.5%"
                    y="-8.1%"
                    width="134.8%"
                    height="122.1%"
                    filterUnits="objectBoundingBox"
                    id="filter-4"
                >
                    <feOffset
                        dx="0"
                        dy="2"
                        in="SourceAlpha"
                        result="shadowOffsetOuter1"
                    ></feOffset>
                    <feGaussianBlur
                        stdDeviation="2"
                        in="shadowOffsetOuter1"
                        result="shadowBlurOuter1"
                    ></feGaussianBlur>
                    <feColorMatrix
                        values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.5 0"
                        type="matrix"
                        in="shadowBlurOuter1"
                    ></feColorMatrix>
                </filter>
                <text
                    id="text-5"
                    font-family="Skia-Regular_Bold, Skia"
                    font-size="48"
                    font-weight="bold"
                    fill="#F06C00"
                >
                    <tspan x="45" y="69">
                        isle
                    </tspan>
                </text>
                <filter
                    x="-9.7%"
                    y="-9.5%"
                    width="119.5%"
                    height="125.9%"
                    filterUnits="objectBoundingBox"
                    id="filter-6"
                >
                    <feOffset
                        dx="0"
                        dy="2"
                        in="SourceAlpha"
                        result="shadowOffsetOuter1"
                    ></feOffset>
                    <feGaussianBlur
                        stdDeviation="2"
                        in="shadowOffsetOuter1"
                        result="shadowBlurOuter1"
                    ></feGaussianBlur>
                    <feColorMatrix
                        values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.5 0"
                        type="matrix"
                        in="shadowBlurOuter1"
                    ></feColorMatrix>
                </filter>
                <text
                    id="text-7"
                    font-family="Skia-Regular_Bold, Skia"
                    font-size="48"
                    font-weight="bold"
                    fill="#F06C00"
                >
                    <tspan x="173" y="69">
                        avigate
                    </tspan>
                </text>
                <filter
                    x="-4.5%"
                    y="-9.5%"
                    width="108.9%"
                    height="125.9%"
                    filterUnits="objectBoundingBox"
                    id="filter-8"
                >
                    <feOffset
                        dx="0"
                        dy="2"
                        in="SourceAlpha"
                        result="shadowOffsetOuter1"
                    ></feOffset>
                    <feGaussianBlur
                        stdDeviation="2"
                        in="shadowOffsetOuter1"
                        result="shadowBlurOuter1"
                    ></feGaussianBlur>
                    <feColorMatrix
                        values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.5 0"
                        type="matrix"
                        in="shadowBlurOuter1"
                    ></feColorMatrix>
                </filter>
            </defs>
            <g
                id="Page-2"
                stroke="none"
                stroke-width="1"
                fill="none"
                fill-rule="evenodd"
            >
                <g id="Custom-Preset-3">
                    <g id="N" stroke="#000000">
                        <use
                            fill="#F06C00"
                            fill-opacity="1"
                            stroke-opacity="1"
                            filter="url(#filter-2)"
                            href="#text-1"
                        ></use>
                        <use
                            fill="#F06C00"
                            fill-opacity="1"
                            stroke-opacity="1"
                            href="#text-1"
                        ></use>
                        <use href="#text-1"></use>
                    </g>
                    <g id="A" stroke="#000000">
                        <use
                            fill="#F06C00"
                            fill-opacity="1"
                            stroke-opacity="1"
                            filter="url(#filter-4)"
                            href="#text-3"
                        ></use>
                        <use
                            fill="#F06C00"
                            fill-opacity="1"
                            stroke-opacity="1"
                            href="#text-3"
                        ></use>
                        <use href="#text-3"></use>
                    </g>
                    <g id="isle" stroke="#000000">
                        <use
                            fill="#F06C00"
                            fill-opacity="1"
                            stroke-opacity="1"
                            filter="url(#filter-6)"
                            href="#text-5"
                        ></use>
                        <use
                            fill="#F06C00"
                            fill-opacity="1"
                            stroke-opacity="1"
                            href="#text-5"
                        ></use>
                        <use href="#text-5"></use>
                    </g>
                    <g id="avigate" stroke="#000000">
                        <use
                            fill="#F06C00"
                            fill-opacity="1"
                            stroke-opacity="1"
                            filter="url(#filter-8)"
                            href="#text-7"
                        ></use>
                        <use
                            fill="#F06C00"
                            fill-opacity="1"
                            stroke-opacity="1"
                            href="#text-7"
                        ></use>
                        <use href="#text-7"></use>
                    </g>
                    <line
                        x1="340.997841"
                        y1="31.9801948"
                        x2="350.5"
                        y2="24.5"
                        id="Line-2"
                        stroke="#445278"
                        stroke-width="5"
                        stroke-linecap="round"
                    ></line>
                    <line
                        x1="310.166746"
                        y1="10.8524148"
                        x2="319.003348"
                        y2="19.2664164"
                        id="Line-2"
                        stroke="#445278"
                        stroke-width="5"
                        stroke-linecap="round"
                    ></line>
                    <line
                        x1="331.999399"
                        y1="24.9693804"
                        x2="338.910697"
                        y2="31.9081413"
                        id="Line-2-Copy-5"
                        stroke="#445278"
                        stroke-width="5"
                        stroke-linecap="round"
                    ></line>
                    <line
                        x1="318.999399"
                        y1="18.9693804"
                        x2="325.910697"
                        y2="25.9081413"
                        id="Line-2-Copy-5"
                        stroke="#445278"
                        stroke-width="5"
                        stroke-linecap="round"
                    ></line>
                    <line
                        x1="329.045982"
                        y1="42.0629285"
                        x2="341.045982"
                        y2="48.0629285"
                        id="topleg3"
                        stroke="#445278"
                        stroke-width="5"
                        stroke-linecap="round"
                    ></line>
                    <line
                        x1="342"
                        y1="50.0081588"
                        x2="342.5"
                        y2="63.5"
                        id="bottomleg3"
                        stroke="#445278"
                        stroke-width="5"
                        stroke-linecap="round"
                    ></line>
                    <ellipse
                        id="Oval"
                        fill="#445278"
                        cx="329.5"
                        cy="12"
                        rx="7.5"
                        ry="7"
                    ></ellipse>
                    <rect
                        id="Rectangle"
                        fill="#445278"
                        x="324"
                        y="19"
                        width="10"
                        height="26"
                        rx="5"
                    ></rect>
                    <line
                        x1="362.926724"
                        y1="50.9169776"
                        x2="365.642241"
                        y2="63.6389925"
                        id="Line"
                        stroke="#666A74"
                        stroke-width="3"
                        stroke-linecap="square"
                        stroke-linejoin="round"
                    ></line>
                    <line
                        x1="368.926724"
                        y1="50.9169776"
                        x2="371.642241"
                        y2="63.6389925"
                        id="Line"
                        stroke="#666A74"
                        stroke-width="3"
                        stroke-linecap="square"
                        stroke-linejoin="round"
                    ></line>
                    <line
                        x1="374.926724"
                        y1="50.9169776"
                        x2="377.642241"
                        y2="63.6389925"
                        id="Line"
                        stroke="#666A74"
                        stroke-width="3"
                        stroke-linecap="square"
                        stroke-linejoin="round"
                    ></line>
                    <line
                        x1="380.926724"
                        y1="50.9169776"
                        x2="383.642241"
                        y2="63.6389925"
                        id="Line"
                        stroke="#666A74"
                        stroke-width="3"
                        stroke-linecap="square"
                        stroke-linejoin="round"
                    ></line>
                    <circle
                        id="Oval"
                        stroke="#33353B"
                        stroke-width="2"
                        cx="362"
                        cy="72"
                        r="3"
                    ></circle>
                    <circle
                        id="Oval"
                        stroke="#33353B"
                        stroke-width="2"
                        cx="382"
                        cy="72"
                        r="3"
                    ></circle>
                    <polyline
                        id="Path"
                        stroke="#666A74"
                        stroke-width="3"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        points="351 48 354.766318 48 356.398184 50.2965116 359.092968 65 384.865412 65 389 50.2965116 357.432818 50.2965116"
                    ></polyline>
                </g>
            </g>
        </svg>
    )
}

export default Header
