import React from 'react'

const LoaderPath = (props) => {
    const { aisleCount, totalAisles } = props

    return (
        <div className="loaderPathContainer">
            <svg
                viewBox="0 0 1024 1024"
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                className="loaderPath"
            >
                <title>Mobile</title>
                <g
                    id="Page-1"
                    stroke="none"
                    strokeWidth="1"
                    fill="none"
                    fillRule="evenodd"
                >
                    <g id="Mobile">
                        <path
                            id="redLine1"
                            d="M0 990 h900 l 100 -100 h-900 z "
                            stroke="black"
                            strokeWidth="1px"
                            fill="red"
                        ></path>

                        <path
                            id="shopSquare"
                            d={`M600 790 h 250 v${
                                (aisleCount / totalAisles) * -500
                            } h-250 z `}
                            stroke="yellow"
                            fill="yellow"
                        ></path>

                        <circle
                            id="Oval"
                            fill="#666A74"
                            cx="350.5"
                            cy="551"
                            r="31"
                        ></circle>
                        <polyline
                            id="Path"
                            stroke="#666A74"
                            strokeWidth="20"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            points="381.5 554 434.922244 554 458.068985 585.34063 496.292361 786 861.854127 786 920.5 585.34063 472.744448 585.34063"
                        ></polyline>
                        <line
                            x1="527.241379"
                            y1="585.75"
                            x2="568.758621"
                            y2="785.25"
                            id="Line"
                            stroke="#666A74"
                            strokeWidth="20"
                            strokeLinecap="square"
                            strokeLinejoin="round"
                        ></line>
                        <line
                            x1="609.241379"
                            y1="585.746269"
                            x2="650.758621"
                            y2="784.253731"
                            id="Line-Copy"
                            stroke="#666A74"
                            strokeWidth="20"
                            strokeLinecap="square"
                            strokeLinejoin="round"
                        ></line>
                        <line
                            x1="693.241379"
                            y1="585.746269"
                            x2="734.758621"
                            y2="784.253731"
                            id="Line-Copy-2"
                            stroke="#666A74"
                            strokeWidth="20"
                            strokeLinecap="square"
                            strokeLinejoin="round"
                        ></line>
                        <line
                            x1="776.258621"
                            y1="585.746269"
                            x2="818.741379"
                            y2="784.253731"
                            id="Line-Copy-3"
                            stroke="#666A74"
                            strokeWidth="20"
                            strokeLinecap="square"
                            strokeLinejoin="round"
                        ></line>
                        <line
                            x1="860.264706"
                            y1="585.74"
                            x2="884.735294"
                            y2="695.26"
                            id="Line-Copy-4"
                            stroke="#666A74"
                            strokeWidth="20"
                            strokeLinecap="square"
                            strokeLinejoin="round"
                        ></line>
                        <path
                            d="M495.821987,787 C447.392671,827 447.392671,847 495.821987,847 C544.251304,847 665.810641,847 860.5,847"
                            id="Path-3"
                            stroke="#666A74"
                            strokeWidth="20"
                        ></path>
                        <circle
                            id="Oval"
                            stroke="#33353B"
                            strokeWidth="15"
                            cx="526.5"
                            cy="900"
                            r="24.5"
                        ></circle>
                        <circle
                            id="Oval-Copy"
                            stroke="#33353B"
                            strokeWidth="15"
                            cx="808.5"
                            cy="900"
                            r="24.5"
                        ></circle>
                        <ellipse
                            id="Oval"
                            fill="#273C75"
                            cx="163.5"
                            cy="274.5"
                            rx="66"
                            ry="66.5"
                        ></ellipse>
                        <rect
                            id="Rectangle"
                            fill="#273C75"
                            x="108"
                            y="346"
                            width="111"
                            height="292"
                            rx="37"
                        ></rect>

                        <line
                            x1="250"
                            y1="512"
                            x2="318.917582"
                            y2="532.168182"
                            id="Line-2"
                            stroke="#273C75"
                            strokeWidth="50"
                            strokeLinecap="round"
                        ></line>
                        <line
                            x1="163.993132"
                            y1="432.680682"
                            x2="242.979396"
                            y2="505.042045"
                            id="Line-2-Copy-5"
                            stroke="#273C75"
                            strokeWidth="50"
                            strokeLinecap="round"
                        ></line>
                        <line
                            x1="165.03"
                            y1="632.276549"
                            x2="220"
                            y2="773"
                            id="topleg2"
                            stroke="#273C75"
                            strokeWidth="60"
                            strokeLinecap="round"
                        ></line>
                        <line
                            x1="153"
                            y1="622.914474"
                            x2="125"
                            y2="772.638158"
                            id="topleg1"
                            stroke="#273C75"
                            strokeWidth="60"
                            strokeLinecap="round"
                        ></line>
                        <line
                            x1="220"
                            y1="773.095395"
                            x2="279"
                            y2="924.180921"
                            id="bottomleg2"
                            stroke="#273C75"
                            strokeWidth="60"
                            strokeLinecap="round"
                        ></line>
                        <line
                            x1="122"
                            y1="774.095395"
                            x2="41"
                            y2="899"
                            id="bottomleg1"
                            stroke="#273C75"
                            strokeWidth="60"
                            strokeLinecap="round"
                        ></line>
                    </g>
                </g>
            </svg>
        </div>
    )
}

export default LoaderPath
